### ISSUE TITLE
Mismatch between lets encrypt folder location and nginx config

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/digitalocean-1-click#4]
The one-click droplet install currently results in lets encrypt certificates at /etc/letsencrypt/domainname_ecc, but Ghost configures Nginx to look for them at /etc/letsencrypt/domainname.  This causes Nginx to not start, resulting in a 'failed install' for new users.

Moving the certificate folder to /etc/letsencrypt/domainname manually allows Nginx to start.

**Comment by daniellockyer** [comment]
Hey @cathysarisky - this should have been fixed by https://github.com/TryGhost/Ghost-CLI/commit/467d41b53d154598dd92fe404321c763e30cf7e1 🙂
